<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 ./static/assets/idwCalculator.glb --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/static/assets/idwCalculator.glb', { useDraco: true });

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cube102.geometry}
      material={gltf.materials['Material.030']}
      position={[-5.63, -0.68, 1.46]}
      rotation={[-1.31, 0, 0]}
      scale={4.19}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube040.geometry}
      material={gltf.materials['Material.014']}
      position={[-5.84, -0.01, 0.24]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube041.geometry}
      material={gltf.materials['Material.029']}
      position={[-5.84, 0.12, 0.79]}
      scale={[0.73, 0.73, 0.33]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
